spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5433/doctor_db
    username: doctor
    password: doctor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka