spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/appointment_db
    username: appointment
    password: appointment

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#server:
#  port: 8083
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      patientService:
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3